// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-upcoming-dates.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_dates_default = defineTool({
  name: "list_upcoming_dates",
  title: "List upcoming dates",
  description: "List the signed-in user's upcoming planned dates from their shared calendar, ordered soonest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max dates to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser(ctx).from("calendar_entries").select("id, date, event_time, title, description, vibe, estimated_cost, duration").gte("date", today).order("date", { ascending: true }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const summary = rows.length === 0 ? "No upcoming dates on the calendar." : rows.map((r) => `\u2022 ${r.date}${r.event_time ? ` @ ${r.event_time}` : ""} \u2014 ${r.title}${r.vibe ? ` (${r.vibe})` : ""}`).join("\n");
    return { content: [{ type: "text", text: summary }], structuredContent: { dates: rows } };
  }
});

// src/lib/mcp/tools/list-saved-date-ideas.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_saved_date_ideas_default = defineTool2({
  name: "list_saved_date_ideas",
  title: "List saved date ideas",
  description: "List date ideas the signed-in user has bookmarked in Midnight & Rose.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max ideas to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("saved_date_ideas").select("id, title, description, vibe, estimated_cost, duration, distance_miles, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const summary = rows.length === 0 ? "No saved date ideas yet." : rows.map((r) => `\u2022 ${r.title}${r.vibe ? ` \u2014 ${r.vibe}` : ""}${r.estimated_cost ? ` (${r.estimated_cost})` : ""}`).join("\n");
    return { content: [{ type: "text", text: summary }], structuredContent: { ideas: rows } };
  }
});

// src/lib/mcp/tools/list-bucket-list.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_bucket_list_default = defineTool3({
  name: "list_bucket_list",
  title: "List couple bucket list",
  description: "List items on the shared couple's bucket list (linked partner scope).",
  inputSchema: {
    include_completed: z3.boolean().optional().describe("Include completed items (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_completed }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("bucket_list").select("id, title, description, completed, completed_at, created_at").order("created_at", { ascending: false });
    if (!include_completed) q = q.eq("completed", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const summary = rows.length === 0 ? "Bucket list is empty." : rows.map((r) => `${r.completed ? "\u2713" : "\u2022"} ${r.title}`).join("\n");
    return { content: [{ type: "text", text: summary }], structuredContent: { items: rows } };
  }
});

// src/lib/mcp/tools/add-bucket-list-item.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_bucket_list_item_default = defineTool4({
  name: "add_bucket_list_item",
  title: "Add bucket list item",
  description: "Add a new item to the couple's shared bucket list. Requires the user to be linked with a partner.",
  inputSchema: {
    title: z4.string().trim().min(1).describe("Short title of the bucket list item."),
    description: z4.string().trim().optional().describe("Optional longer description.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const userId = ctx.getUserId();
    const { data: link, error: linkErr } = await sb.from("partner_links").select("id").limit(1).maybeSingle();
    if (linkErr) return { content: [{ type: "text", text: linkErr.message }], isError: true };
    if (!link) return { content: [{ type: "text", text: "You need to link a partner before adding bucket list items." }], isError: true };
    const { data, error } = await sb.from("bucket_list").insert({ partner_link_id: link.id, added_by: userId, title, description: description ?? null }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Added "${data.title}" to your bucket list.` }], structuredContent: { item: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "znvyttxbxkvtyegjiwxj";
var mcp_default = defineMcp({
  name: "midnight-and-rose-mcp",
  title: "Midnight & Rose",
  version: "0.1.0",
  instructions: "Tools for the Midnight & Rose date-planning app. Use these to read the signed-in user's upcoming planned dates, saved date ideas, and shared couple bucket list, or to add a new bucket list item. All tools act as the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_upcoming_dates_default, list_saved_date_ideas_default, list_bucket_list_default, add_bucket_list_item_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
